#@trainote_api_HostAddress = http://localhost:5170

#GET {{trainote_api_HostAddress}}/weatherforecast/
#Accept: application/json

GET "http://localhost:5170/api/usuario/"

### Enviar usuário com imagem
POST "http://localhost:5170/api/usuario/"
multipart(
    'nome' < 'lucastesteauth',
    'email' < 'testestestse@auth',
    'foto' < 'D:\foto-video\chapada-11-01-25\fotos\1736738205403.jpg'
)


POST "http://localhost:5170/api/usuario/7/download"
"Accept" : "image/png"
>> "S:/git/trainotes/trainotes-back/trainote-api/Storage/Downloads"

POST http://localhost:5170/api/v1/auth
? username = "teste"
? password = "teste"
